### ISSUE TITLE
Regionhax is not needed due to marco-calautti's regionfree patch via iosuhax fw.img

### ISSUE THREAD

**Issue by jaxrogers2** [FlimFlam69/WiiUTutorial#3]
This is in the latest commit of dimok's iosuhax seen here at https://github.com/dimok789/iosuhax/commits/master, so regionhax is not needed anymore.

Also, you might want to add a guide on how to install regionhax due to this. Using the uninstaller version of this script on https://gbatemp.net/threads/release-regionhax-installer-noob-friendly.449036/ should work just fine, it just requires Python 2.7 instead of 3.

**Comment by FlimFlam69** [comment]
I'm working on it. I will be keeping Regionhax around for a little while longer only because it's useful if you want your sysNAND region free. (I understand it is somewhat dangerous, but the brick warning will stay). The Regionhax section is prefaced with a note letting users know it's unnecessary. I'm striking any other sentence recommending/ pointing to Regionhax.

I just wished the guy used 3.5 for the un/installer as other guides (like FIX94's and WiiUBat) use 3.5. I'd really hate to conflict with everything else... but 2.7 is making more and more sense to me.

edit: I'll switch to python 2.7. I'm working on it.

**Comment by FlimFlam69** [comment]
* I've made Python 2.7 standard to streamline the Haxchi/ Regionhax processes.
* I've kept Regionhax in the guide as it is useful for people who want sysNAND to be region free, and it's not known to conflict with Dimok's Regionhax patches.
* I've added disclaimers to the Regionhax section letting people know that they don't need to install it if they're gonna be using Dimok's IOSUhax
* For people who want to uninstall Regionhax, I've added a guide on that too.
